swagger: "2.0"
info:
  description: "The goal of the component consists in filtering bluprints and raking them, based on the application developer requirements. Source code in [github](https://github.com/DITAS-Project/data-utility-resolution-engine)"
  version: "0.0.1"
  title: "Data Utility Resolution Engine"
  license:
    name: "License TBD"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "TBD"
basePath: "/"
schemes:
- "http"
paths:
  /filterBlueprints:
    post:
      summary: "Ranks and filters abstract blueprints based on application requirements"
      description: "The only API of this method filters a list of blueprints (input) that are complaint with the application requirements (input), and ranks them."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Input"
        description: "Application requirements and list of VDC blueprints. Both imput marged in the same body because at most 1 body parameter can be defined. [Click here for more info](https://github.com/swagger-api/swagger-editor/issues/889)"
        required: true
        schema:
          $ref: "#/definitions/input"

      responses:
        200:
          description: "Filtered Blueprints"
          schema:
            $ref: '#/definitions/output'
          

definitions:
  applicationRequirements:
    properties:
      name:
        type: string
      tag:
        type: string   

  Blueprint:
    properties:
      name:
        type: string
      tag:
        type: string   

  candidates:
    properties:
      Blueprint:
        $ref: "#/definitions/Blueprint"
      MethodName:
        type: string
          
  input:
    properties:
      candidates:
        type: "array"
        items: 
          $ref: "#/definitions/candidates"
      applicationRequirements:
        $ref: "#/definitions/applicationRequirements"
        
  output:
    type: "array"
    items: 
      properties:
        BlueprintUUID:
          type: string
        MethodName:
          type: string
        Score:
          type: number
          format: double
          minimum: 0
          maximum: 1
        FulfilledRequirements:
          $ref: "#/definitions/applicationRequirements"
